Image upload
otofune/mozuku pull request #142
Opened 2019-06-17 15:19 UTC by motitaiyaki

Resolves #51 

改善点
- [ ] アップロード中表示
- [ ] クリップボードからの貼り付けを用いたアップロード
- [ ] すべて

2019-06-18 03:07 UTC, motitaiyaki commented
[https://github.com/otofune/mozuku/issues/51#issuecomment-501278276]() を参考に。各位の意見ほしい
![localhost_1234_(1280x720) (2)](https://user-images.githubusercontent.com/7887955/59650611-9968ab00-91c1-11e9-9a4b-e365cfc46faa.png)

2019-06-18 05:32 UTC, p-chan commented
少しデザインの候補っぽいものを作ってみた（細かいステートによる変化まで考慮してないので、このデザインを採用する場合はもう少し議論したい）

<img width="801" alt="Screen Shot 2019-06-18 at 14 22 09" src="https://user-images.githubusercontent.com/7752475/59655413-26692f80-91d5-11e9-9277-e92d12f6ae05.png">
<img width="790" alt="Screen Shot 2019-06-18 at 14 22 20" src="https://user-images.githubusercontent.com/7752475/59655414-26692f80-91d5-11e9-8c2a-e85efbb31363.png">

2019-06-21 18:12 UTC, otofune requested changes
すごく使いやすいです！感謝します。ですが、気になる点があります

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/PostForm/index.tsx
> +    const onBlur = (event: React.FocusEvent<HTMLFormElement>) => {
これはなぜ必要ですか？

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/PostForm/index.tsx
> +    const onFocus = (event: React.FocusEvent<HTMLFormElement>) => {
うごいてるけど iOS beta だと最悪な挙動になってそう（IME が出るときにスクロールするのとカチあって位置が戻る）

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/PostForm/index.tsx
> +        window.scrollTo(0, event.currentTarget.offsetTop)
消し忘れかな、scrollItoView 使うなら消してほしい
https://caniuse.com/#feat=scrollintoview では IE 11 から対応してそう
sctollIntoView が使えなかった場合関数ではないとエラーが出て処理が止まりそうなのでなんにせよ無意味っぽい

```suggestion
```

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/PostForm/index.tsx
> +              <i className={`uil uil-polygon ${styles.spin}`} />
👍

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/PostForm/index.tsx
> +              disabled={draftDisabled}
isUploading でも無効にしてください

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/index.tsx
> +  const uploadAlbumFile = async (file: File) => {
useCallback 使ってください

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/index.tsx
> +  const uploadAlbumFile = async (file: File) => {
presenter にロジック書かないでください

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/index.tsx
> +  const [files, setFiles] = useState([] as AlbumFile[])
presenter にドメインロジックに関係するステートは持たないでください

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/index.tsx
> +      .filter(file => file.type.split('/').shift() == 'image')
[重要ではない] 次の方が簡潔そうです
```suggestion
      .filter(file => file.type.startsWith(‘image/‘))
```

2019-06-21 18:12 UTC, otofune commented on src/util/seaClient.ts
> +    return this.createAxiosInstance(state)
createInstance 時にやるのではなく作ったインスタンスを呼び出す際、第三引数にオプションで渡してください。axios インスタンスでも config は設定できます。
https://github.com/axios/axios/blob/master/examples/upload/index.html

あくまでプリセットの設定を提供するための関数とみなしていてこれが入ることで見通しが悪くなること、各呼び出しで axios は設定の変更を受け付けるためです

2019-06-21 18:12 UTC, otofune commented on src/stores/app.ts
> +  ): Promise<AlbumFile> {
❤️

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/index.tsx
> +import { appStore } from '../../stores'
presenter から直接 appStore を参照しないでください

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/index.css
> +.progressContainer {
[メモ] プログレスバーを重ねたい。
わからないけど height:0 とかにすると陥没しそう。あとで試す

2019-06-21 18:12 UTC, otofune commented on src/containers/Home/PostForm.tsx
> +    setFiles(files.filter(file => file.id != fileId))
[メモ] あとでファイル削除するようにしたい

2019-06-21 18:12 UTC, otofune commented on src/containers/Home/PostForm.tsx
> +    if (!draftDisabled) {
return early してください。見通しが良くなります

```suggestion
    if (draftDisabled) return
```

2019-06-21 18:12 UTC, otofune commented on src/containers/Home/PostForm.tsx
> +    if (draft.trim().length > 0 || 1 <= files.length) {
ファイルがあれば本文が空でも送信できる :+1:

2019-06-21 18:12 UTC, otofune commented on src/presenters/Home/index.tsx
> +    setIsUploading(false)
[提案] もしアプリケーションワイドにアップロードロックするなら appStore においてはどうでしょうか。prop バケツリレーはとても大変です

2019-06-21 18:29 UTC, otofune commented on src/presenters/Home/PostForm/index.tsx
> +    const onFocus = (event: React.FocusEvent<HTMLFormElement>) => {
これいろいろなデバイスで動かしてみて、あんまり嬉しくなさそうなら消したい

2019-06-22 00:36 UTC, rinsuki commented on src/containers/Home/PostForm.tsx
> +    if (draft.trim().length > 0 || 1 <= files.length) {
動的な値を左に持ってくるのか静的な値を左に持ってくるのかは統一したほうがよさそう

2019-06-22 02:24 UTC, motitaiyaki commented on src/presenters/Home/PostForm/index.tsx
> +    const onFocus = (event: React.FocusEvent<HTMLFormElement>) => {
`scrollItoView` iOS Beta で最悪の挙動をしているので代替として追加したのの `scrollIntoView` 消し忘れです

2019-06-22 02:25 UTC, motitaiyaki commented on src/presenters/Home/PostForm/index.tsx
> +    const onBlur = (event: React.FocusEvent<HTMLFormElement>) => {
Rows での制御を行っていたときの残骸、不要なので消します

2019-06-22 02:30 UTC, motitaiyaki commented on src/containers/Home/PostForm.tsx
> +    if (draft.trim().length > 0 || 1 <= files.length) {
左に持ってくるようにした

2019-06-22 02:31 UTC, motitaiyaki commented on src/containers/Home/PostForm.tsx
> +    if (draft.trim().length > 0 || 1 <= files.length) {
これ手元では既に書き加えられてるんですがどういうことなんだろう、下記指摘どおり左に統一

2019-06-22 02:40 UTC, motitaiyaki commented on src/util/seaClient.ts
> +    return this.createAxiosInstance(state)
引数を削除

2019-06-22 02:56 UTC, motitaiyaki commented on src/presenters/Home/index.tsx
> +import { appStore } from '../../stores'
99a7e83

2019-06-22 02:56 UTC, motitaiyaki commented on src/presenters/Home/index.tsx
> +  const [files, setFiles] = useState([] as AlbumFile[])
99a7e83

2019-06-22 02:58 UTC, motitaiyaki commented on src/presenters/Home/index.tsx
> +  const uploadAlbumFile = async (file: File) => {
99a7e83
useCallback の具体的な用法がわからず、教えて欲しい

2019-06-22 03:00 UTC, motitaiyaki commented on src/presenters/Home/index.tsx
> +    setIsUploading(false)
実は draft も appStore に置くべき？

2019-06-22 03:06 UTC, motitaiyaki commented on src/presenters/Home/index.css
> +.progressContainer {
重なった

2019-06-22 03:31 UTC, motitaiyaki commented on src/presenters/Home/index.tsx
> +    setIsUploading(false)
oita f342288

2019-06-22 03:39 UTC, otofune commented on src/presenters/Home/PostForm/index.tsx
> +    const onFocus = (event: React.FocusEvent<HTMLFormElement>) => {
理解

2019-06-22 18:47 UTC, otofune requested changes
container は css などを持たない上独立しているので、`contatiner/` 直下にファイルで作成してください。他はそうなっているはずです。
これまで `Home/` 以下にあったのは, Home コンポーネントからしか呼びだされないという意味で置いているのであって、Home コンポーネントそのものは独立して機能できるという見解です

2019-06-22 18:47 UTC, otofune commented on src/containers/Home/Index.tsx
> +    appStore.setIsUploading(true)
これ appStore.uploadAlbumFile に処理入れる方が好ましいと思う

2019-06-22 18:47 UTC, otofune commented on src/containers/Home/Index.tsx
> +  const [isDrop, setIsDrop] = useState(false)
cotainer -> presener -> container でバケツリレーが発生するときシンプルさに欠け最悪だと思っているので、こうなるなら isDrop はいいけど uploadState, files, draftDisabled, draft は全部 appStore に置いてほしい
あるいは、ドラッグ先を PostForm に限定してほしい

2019-06-22 18:47 UTC, otofune commented on src/containers/Home/Index.tsx
> +  const [isDrop, setIsDrop] = useState(false)
それはそれでどうなの? というのはあるが、少なくともバケツリレーするよりマシだと思っています

2019-06-22 18:47 UTC, otofune commented on src/containers/Home/Index.tsx
> +  const [isDrop, setIsDrop] = useState(false)
私としては PostForm に閉じこめたいです

2019-06-22 18:47 UTC, otofune commented on src/containers/Home/Index.tsx
> +  const [isDrop, setIsDrop] = useState(false)
あるいは, PostForm を独立するのをやめて presenter/Home/PostForm にし、直接 container/Home から呼ぶとよさそう

2019-06-22 18:48 UTC, otofune commented
@motitaiyaki  気持ちがなくなったらこちらでリファクタリングやります、細かいけど譲れないところです 🙇

2019-06-22 19:32 UTC, otofune commented
あーーーこのリファクタリング俺がやります。#44 対応するためにも必要なので

2019-06-22 19:33 UTC, otofune approved these changes
💯

2019-06-22 19:33 UTC, merged