feat: add image-size text at lower right of an image
otofune/mozuku pull request #180
Opened 2019-07-15 11:10 UTC by motitaiyaki

追加
- [x] 画像クリック時モーダルに展開されるべき画像のサイズ（画像の右下）
- [x] 添付ファイル数（投稿テキストの下）

気になる点
- [ ] 添付ファイル数の場所とそもそもの必要性（必要性に関してはあれば便利かなという程度）

2019-07-15 11:28 UTC, atnanasi commented on src/presenters/Post/Image/image.css
> +.image__size p {
```suggestion
.imageSize p {
```

2019-07-15 11:28 UTC, atnanasi commented on src/presenters/Post/Image/index.tsx
> +                <div className={styles.image__size}>
```suggestion
                <div className={styles.imageSize}>
```

2019-07-15 11:32 UTC, atnanasi commented
代案が出せなくて申し訳ないんですが、divで.imageと.imageSizeを囲ってるのが微妙にキモいかなーと思った、imageContainerとかで括って適切にスタイル当てたほうが構造として良いよねといった感じ

2019-07-15 11:34 UTC, atnanasi commented
![image](https://user-images.githubusercontent.com/6058487/61213385-e0ee4280-a73f-11e9-808a-8ab60aff118f.png)
UIヤバくない?

2019-07-15 11:34 UTC, motitaiyaki commented
なぜかテスト通ってるけどさっきのsuggestion commitでぶち壊れた 修正した

2019-07-15 12:14 UTC, atnanasi commented
単数の時にattachmentsじゃなくてattachmentって出したいね

2019-07-15 12:16 UTC, otofune commented
attachment 表示は不要と思っています。IMO ですが、正直多くの画像を添付するユーザーはいないことが多いというのと、単にスクロールすれば見れるので……
よくあるスクロールしそうなことを予見できる影みたいなものを表示限界量より多く画像が添付されていればつけるみたいなところはあっても良いと思っていますが別の議論だと思います

2019-07-15 13:12 UTC, motitaiyaki commented
- 添付ファイル数を削除
- 画像のツリー構造を直して丸めを修正

2019-07-15 15:18 UTC, rokoucha approved these changes
👍

2019-07-15 15:55 UTC, otofune requested changes

2019-07-15 15:55 UTC, otofune commented on src/presenters/Post/Image/image.css
>    border-radius: var(--image-border-radius-small);
これ消してほしい！
```suggestion
```

2019-07-15 15:56 UTC, motitaiyaki commented on src/presenters/Post/Image/image.css
>    border-radius: var(--image-border-radius-small);
え、丸まらなくてもよいということ？

2019-07-15 16:02 UTC, otofune commented on src/presenters/Post/Image/image.css
>    border-radius: var(--image-border-radius-small);
あーごめん。imageSize にも別でつけてるだけなら必要だわ..

2019-07-15 16:04 UTC, rokoucha requested changes
![image](https://user-images.githubusercontent.com/6058487/61230763-a9928c80-a765-11e9-9b31-42938e070922.png)

2019-07-18 06:32 UTC, otofune approved these changes
いいと思います
.image を border-radius できれば平和なのに……と思って試してたけどなにもできなかった

2019-07-18 06:36 UTC, rokoucha approved these changes
対応ありがとうございます!

2019-07-18 06:39 UTC, merged