feat: Add service worker for PWA
otofune/mozuku pull request #206
Opened 2019-08-09 07:25 UTC by atnanasi

2019-08-09 07:30 UTC, atnanasi commented
A2HSが出てこない件は確認中

2019-08-09 07:35 UTC, atnanasi commented
出てくる事を確認
![image](https://user-images.githubusercontent.com/6058487/62762286-b8016900-bac3-11e9-9d39-12ca8dc3cbbe.png)

2019-08-10 03:28 UTC, otofune requested changes

2019-08-10 03:28 UTC, otofune commented on src/serviceworker.ts
> +/// <reference types="../node_modules/types-serviceworker" />
デフォルトで入ってるモジュールじゃないので追加してください

2019-08-10 06:28 UTC, atnanasi commented on src/serviceworker.ts
> +/// <reference types="../node_modules/types-serviceworker" />
この対応ではモジュールが不必要だったので削除。

2019-08-10 10:01 UTC, otofune approved these changes

2019-08-10 10:01 UTC, merged