Use GitHub Actions
otofune/mozuku pull request #344
Opened 2019-11-13 10:09 UTC by rinsuki

close #343

2019-11-13 10:19 UTC, ci7lus reviewed
[imo]
- [x] キャッシュを用いるほうがいいかも？
- [x] ~~lint, build, test は分けるべきかも？~~ と思ったが現状の workflow だと分けないほうが良さそう
- [x] 全 push で発動しても特段問題なさそう？

2019-11-13 10:20 UTC, rinsuki commented
全pushで発動にすると同一repo内pullreqやるときにpushとpull_requestで二重に走って悲しい気持ちになる

2019-11-13 10:20 UTC, ci7lus commented
そうなんだ…

2019-11-13 10:21 UTC, rinsuki commented
キャッシュについてはとりあえず1分越えなければわざわざやらなくていいのではという気持ちがある (どうせdependabotには効かないし)

2019-11-13 10:22 UTC, ci7lus requested changes
まあそれもそうか…

2019-11-13 10:22 UTC, ci7lus submitted a review, later dismissed
ミスった

2019-11-14 05:56 UTC, tosuke submitted a review, later dismissed

2019-12-04 15:17 UTC, otofune approved these changes

2019-12-04 15:18 UTC, otofune commented on .github/workflows/node.yml
> +  push:
push だけでいいのでは?

2019-12-04 15:19 UTC, otofune commented on .github/workflows/node.yml
> +      run: yarn prettier --check "./src/**/*.{html,css,ts,tsx}"
yarn prettier でよいです

2019-12-04 15:19 UTC, otofune requested changes
prettier つかってほしい

2019-12-04 15:28 UTC, otofune commented on .github/workflows/node.yml
> +  push:
これはどっちでもいいですね

2019-12-05 01:18 UTC, rinsuki commented on .github/workflows/node.yml
> +  push:
- 別リポジトリが元のプルリクを出されたときに回る用に `pull_request` は必須
- pushで無条件に走らせると同リポジトリ内pullreqで二重に回る

のでpushはmasterだけに絞ってある

2019-12-05 01:26 UTC, rinsuki commented on .github/workflows/node.yml
> +      run: yarn prettier --check "./src/**/*.{html,css,ts,tsx}"
実はtestで`yarn prettier --check`してるしそれでよくね?説がありますがどうですか

2019-12-05 02:11 UTC, otofune commented on .github/workflows/node.yml
> +      run: yarn prettier --check "./src/**/*.{html,css,ts,tsx}"
@rinsuki package.json に prettier が定義してあってすでに対象ファイルも指定しているので二重管理になって嫌、という意図があります

2019-12-05 02:12 UTC, otofune commented on .github/workflows/node.yml
> +      run: yarn prettier --check "./src/**/*.{html,css,ts,tsx}"
https://github.com/linkage-community/mozuku/blob/master/package.json#L55

2019-12-05 04:11 UTC, rinsuki commented on .github/workflows/node.yml
> +      run: yarn prettier --check "./src/**/*.{html,css,ts,tsx}"
その後testも走ってて、そのtest内でprettier --checkしてるので実はここ消しても良いのでは、という意

2019-12-05 05:59 UTC, otofune commented on .github/workflows/node.yml
> +      run: yarn prettier --check "./src/**/*.{html,css,ts,tsx}"
そういうこと? 正しそう

2019-12-06 03:49 UTC, otofune commented on .github/workflows/node.yml
> +      run: yarn prettier --check "./src/**/*.{html,css,ts,tsx}"
なおした

2019-12-06 03:55 UTC, otofune approved these changes
おしちゃう

2019-12-06 03:57 UTC, merged