feat: Add forever scroll
otofune/mozuku pull request #365
Opened 2019-12-04 10:04 UTC by ci7lus

Partial resolves: #151

2019-12-04 10:19 UTC, otofune reviewed
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API 使うといいかもしれません

2019-12-04 10:21 UTC, rinsuki requested changes
あとロード中かどうか表示したほうがよさそう

2019-12-04 10:21 UTC, rinsuki commented on src/containers/local-timeline/timeline.tsx
> +      if (scrolled < 1000 && !timelineStore.readMoreDisabled) {
FullHDディスプレイで最大化したときに一番下までスクロールしても `document.body.scrollHeight - window.scrollY` が1000を越えるのでRead moreが発火しない (heightを考慮するべきっぽそう)

2019-12-04 10:23 UTC, rinsuki commented
あと普通にread moreボタンは残しておいても良い気がする

2019-12-04 10:25 UTC, rinsuki commented
というか opt-out ableであってほしい (個人の感想です)

2019-12-04 10:29 UTC, rinsuki commented
あとオフラインの時にちょっとスクロールするだけでリクエスト投げまくるのはあんまりよくなさそう (オフラインならいいがサーバーの高負荷起因のエラーとかだと泣きそう)

2019-12-04 14:45 UTC, rinsuki approved these changes

2019-12-06 03:46 UTC, otofune approved these changes

2019-12-06 03:47 UTC, merged